### ISSUE TITLE
Release as npm

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/webExtNativeMsg#2]

**Comment by asamuzaK** [comment]
Depends on #1

**Comment by DamienCassou** [comment]
I would like that as well. Thank you.

**Comment by DamienCassou** [comment]
Would it be possible to release in npmjs.com without the unit-tests? I would like to see the release happen sooner rather than later if that's possible.

**Comment by asamuzaK** [comment]
If I don't write tests now, after releasing it, I'm pretty sure I probably won't write them... :P

**Comment by asamuzaK** [comment]
To be honest, I was thinking that there is not much meaning to release as npm until node.js v8 becomes LTS, what do you think?

**Comment by asamuzaK** [comment]
Released
[web-ext-native-msg](https://www.npmjs.com/package/web-ext-native-msg "web-ext-native-msg")

**Comment by DamienCassou** [comment]
> To be honest, I was thinking that there is not much meaning to release as npm until node.js v8 becomes LTS, what do you think?

I think it's ok to release a library before one of its dependencies if it's made clear what are the requirements.

> Released: web-ext-native-msg

Thank you very much

**Comment by asamuzaK** [comment]
Note that package name changed to "web-ext-native-msg".
npm didn't allow capital letters...
