### ISSUE TITLE
Support chrome canary

### ISSUE THREAD

**Issue by mantou132** [asamuzaK/webExtNativeMsg#21]
Shares host with Chrome?

**Comment by asamuzaK** [comment]
At least on Windows, yes.

**Comment by mantou132** [comment]
macOS  does not share.

Should use:
`/Users/xxx/Library/Application Support/Google/Chrome Canary/NativeMessagingHosts/xxx.json`

**Comment by asamuzaK** [comment]
Thanks I'll add support for chrome canary.
