### ISSUE TITLE
Chrome/Chromium on Linux not connected to host

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/webExtNativeMsg#36]
See [error starting -&gt; not a terminal vim · Issue #116 · asamuzaK/withExEditor](https://github.com/asamuzaK/withExEditor/issues/116)

**Comment by asamuzaK** [comment]
* [x] Install VitualBox
* [x] Install Ubuntu 16.04 LTS
* [x] Install Node.js (10.15.3)
* [x] Install withexeditorhost
* [x] Setup host for chromium
* [x] Install chromium `sudo apt install chromium-browser`

Then I ran Chromium and host get connected.
But when I looked into the version, I noticed that Chromium is a bit old.

```
$ chromium-browser --version
Chromium 73.0.3683.86 Built on Ubuntu , running on Ubuntu 16.04
```

@OrionRandD
How can I update Chromium to the latest version?

**Comment by asamuzaK** [comment]
Confirmed that Vivaldi get connected too.
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.158 Safari/537.36 Vivaldi/2.5.1525.43`

**Comment by OrionRandD** [comment]
So, it seems that there is something wrong in my config for chromium,
somewhere here.

Version 74.0.3729.108 (Developer Build) built on Debian 10.0, running on Debian 10.0 (64-bit)

**Comment by asamuzaK** [comment]
Brave is okay too.

I need a step to reproduce this issue.

**Comment by asamuzaK** [comment]
A possible scenario is that Chromium is not reading `~/.config/chromium/` at all.
Is there any other place where Chromium settings are stored?

**Comment by asamuzaK** [comment]
Found a way to update Chromium and it still get connected to host.
`Chromium 74.0.3729.169 Built on Ubuntu , running on Ubuntu 16.04`

**Comment by asamuzaK** [comment]
Can't reproduce the issue.
I will treat this issue as invalid and close it at the moment.

If there is any new information, feel free to reopen.
